### ISSUE TITLE
[2.0.0] MQTT geht nicht

### ISSUE THREAD

**Issue by reibuehl** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#10]
In der Version 2.0.0 scheint MQTT garnicht mehr zu gehen. Die mqtt_connect() Funktion wird anscheinend garnicht mehr aufgerufen.

Ich denke mal, dass es an dem 

    if (!strcmp(cfg.mqtt_broker_address, "127.0.0.1")) {
      mqtt_connect();
    }

in NetworkManager.cpp liegt. mqtt_broker_address ist bei mir auf 192.168.1.2 gesetzt (laut dem Config Webserver), der erste Serial.print in mqtt_connect() kommt aber nicht, daher denke ich mal, dass die Funktion gar nicht angesprungen wird.

**Comment by reibuehl** [comment]
Ich hab probeweise mal die NetworkManager.cpp so geändert, dass der Test auf mqtt_broker_address nicht mehr ausgeführt wird und damit funktioniert MQTT wieder:
  
```
// if (!strcmp(cfg.mqtt_broker_address, "127.0.0.1")) {
    mqtt_connect();
//}

```

**Comment by awatterott** [comment]
`strcmp()` liefert 0 bei Gleichheit und daher muss die Invertierung entfernt werden: `if (strcmp(cfg.mqtt_broker_address, "127.0.0.1"))`
Damit soll verhindert werden, dass `mqtt_connect()` auf `127.0.0.1` ausgeführt wird.

**Comment by reibuehl** [comment]
Soll ich dafür noch eine PR machen oder änderst Du das selbst?

Vielleicht sollte man dann einen 2.0.1 Release machen...

**Comment by mariolukas** [comment]
Danke euch beiden. Am besten du machst einen PR. Ich würde dann heute Abend alles noch mal fix testen und dann  ein neues Release aus dem PR machen.

**Comment by reibuehl** [comment]
Ist wohl schon von Andreas geändert. Du kannst also heute Abend testen.
