### ISSUE TITLE
eduroam - WPA2 Enterprise (PEAP-MSCHAPv2) Zugang möglich?

### ISSUE THREAD

**Issue by cgienke** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#17]
Ich finde die Firmware richtig gut. Die MQTT-Funktionalität ist sehr hilfreich.
Bei den WiFi-Einstellungsmöglichkeiten würde ich mich über die Möglichkeit freuen, wenn man auch einen Zugang zu einem eduroam-Netzwerk herstellen könnte. Hierzulande wird dafür u.a. das Wurzelzertifikat T-Telesec Global Root Class 2 ([Link zum DFN](https://www.pki.dfn.de/wurzelzertifikate/globalroot2/)) genutzt. Kann man da was machen?

**Comment by mariolukas** [comment]
Das hängt von der verwendeten WiFi Library ab. 
https://github.com/arduino-libraries/WiFi101
Es gab ein Issue dazu. Aber ich glaube viel ist da nicht passiert. Solange die Lib das nicht unterstützt wird auch die Co2 Ampel das leider nicht können.
https://github.com/arduino-libraries/WiFi101/issues/199

**Comment by mariolukas** [comment]
Leider erst mal nicht vorgesehen, weil es von WIFI101 nicht unterstützt wird. Sobald es da Aussicht gibt, kann das ganze gerne noch mal aufgenommen werden. Vorerst schließe ich das Issue mal.
