### ISSUE TITLE
MQTT publishing format – InfluxDB line protocol/JSON

### ISSUE THREAD

**Issue by velkoff** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#18]
Hello,
thank you for the great work! 

It seems that the [Docker-CO2-Monitoring](https://github.com/mariolukas/Docker-CO2-Monitoring) setup expects data in the InfluxDB line protocol, but recently the firmware MQTT publishing format was [amended to JSON](https://github.com/mariolukas/Watterott-CO2-Ampel-Plus-Firmware/commit/a7ba7d71ee55f24e25670d716d68dbb4484e7108#diff-6d1549cf795a6084f79f62db56f50e19659c5778dd99dc462cab9a36676e15a8R36). 

Is this a known issue? 

Thanks,
Vlad

**Comment by mariolukas** [comment]
Yes you are right, seems that the format changed. I will try to add a selection option for the format.

**Comment by mariolukas** [comment]
I fixed it. You are able to  choose the data format (JSON or influx) now. Just try the latest Release[ v.2.1.0](https://github.com/mariolukas/Watterott-CO2-Ampel-Plus-Firmware/releases/tag/v.2.1.0). The Docker 
Co2 Monitoring project was also updated. The default MQTT port is now 1884 to prevent collision with 
other MQTT brokers in the local network.
