### ISSUE TITLE
Eingabe des MQTT Topics

### ISSUE THREAD

**Issue by reibuehl** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#2]
Wäre es möglich, das MQTT Topic als konfigurierbaren Wert in die AP-Mode Konfigurationsseite mit aufzunehmen?
Vielleicht mit dem Namen des MQTT Clients als möglicher Variable? So ähnlich wie das zum Beispiel Tasmota macht.

**Comment by mariolukas** [comment]
Ist in Version 2.0.0 drin.
