### ISSUE TITLE
Wifi Passortlänge ist auf 24 Zeichen begrenzt

### ISSUE THREAD

**Issue by allusernamesalreadytaken** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#22]
Hallo,

die Wifi Passwortlänge scheint bei Eingabe im AP Modus, ohne Warnung/Hinweis auf 24 Zeichen begrenzt zu sein.
Das hat mich jetzt zwei Abende gekostet bis ich mal nachgezählt habe, wieviele Zeichen in das Feld reinpassen.

Gibt es hierfür eine Grund? Kann ich das irgendwie umgehen? Ich nutze i.d.R. 64 Zeichen für mein Wifi und würde das gerne so beibehalten. Würde mich über jede Hilfe freuen.

Danke!

**Comment by mariolukas** [comment]
Ich kann es mir anschauen und die zulässige Länge erhöhen. Ein Hinweis auf die Länge ist auch eine gute Idee.

**Comment by mariolukas** [comment]
Wo kommen die 24 Zeichen her? In der Firmware sind bis zu 40 Zeichen erlaubt (was natürlich nicht das Problem löst).

https://github.com/mariolukas/Watterott-CO2-Ampel-Plus-Firmware/blob/main/CO2-Ampel_Plus/DeviceConfig.h#L8

Das HTML Formular ist nicht in der Länge beschränkt.

https://github.com/mariolukas/Watterott-CO2-Ampel-Plus-Firmware/blob/main/CO2-Ampel_Plus/NetworkManager.cpp#L389

Von daher sollte es Ausreichen wenn die Zeichenlänge von 40 auf 64 Zeichen erhöht wird. Das müsste in den folgenden Zeilen gemacht werden:

https://github.com/mariolukas/Watterott-CO2-Ampel-Plus-Firmware/blob/main/CO2-Ampel_Plus/DeviceConfig.h#L8

und 

https://github.com/mariolukas/Watterott-CO2-Ampel-Plus-Firmware/blob/main/CO2-Ampel_Plus/NetworkManager.cpp#L196

**Comment by allusernamesalreadytaken** [comment]
Ich habe glaub ich mein Passwort in das HTML Feld kopiert und abgezählt wieviele Zeichen da danach stehen bleiben. Wenn ich mich recht erinnere, konnten auch keine weiteren Zeichen hizugefügt werden. Komme gerade leider nicht in den AP Modus, weil ich keinen Laptop da habe.
 
Und sorry das mit den 40 Zeichen im Quellcode habe ich mittlerweile auch gefunden. (Bin aber ein noob und weiß nicht was ich tue, hoffentlich kann ich da nichts kaputt machen)
Habe das bei mir probeweise auf 70 erhöht und das Passwort + SSID direkt in Quellcode eingefügt. Das scheint soweit zu funktionieren. Auch wenn die Ampel die Wifi-Verbindung meist nach ein paar Stunden verliert und scheinbar danach nicht wieder aufnehmen kann. Das ist aber vermutlich ein anderes Problem.

**Comment by mariolukas** [comment]
Sollte behoben sein.
