### ISSUE TITLE
Fehlermeldung im Arduino IDE

### ISSUE THREAD

**Issue by Enoch23** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#26]
Ich habe alles entsprechend konfiguriert und bekomme trotzdem diese Fehlermeldung:

`The current selected board needs the core 'arduino:arduino' that is not installed.`

Was fehlt denn noch?

**Comment by awatterott** [comment]
Man muss auch noch die `Arduino SAMD Boards` neben dem `CO2-Ampel Board` über den Boards Manager installieren.

**Comment by Enoch23** [comment]
Danke. Dachte ich hatte das bereits installiert. Mein Fehler.
