### ISSUE TITLE
JC_Button.h fehlt?

### ISSUE THREAD

**Issue by Enoch23** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#27]
Ich erhalte dazu folgende Fehlermeldung:

`CO2-Ampel_Plus:24:23: fatal error: JC_Button.h: No such file or directory
 #include <JC_Button.h>
                       ^
compilation terminated.
exit status 1
JC_Button.h: No such file or directory`

**Comment by Enoch23** [comment]
Ich hatte das falsche Board ausgewählt. ^^

Jetzt erhalte ich folgende Fehlermeldung:

`In file included from /Users/pilgrim/Library/Arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/samd21/include/samd21.h:69:0,
                 from /Users/pilgrim/Library/Arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/samd.h:105,
                 from /Users/pilgrim/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/Arduino.h:35,
                 from /Users/pilgrim/Downloads/Watterott-CO2-Ampel-Plus-Firmware-v.2.2.0/CO2-Ampel_Plus/CO2-Ampel_Plus.ino:23:
/Users/pilgrim/Library/Arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/samd21/include/samd21g18a.h:237:10: fatal error: core_cm0plus.h: No such file or directory
 #include <core_cm0plus.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board CO2-Ampel.
`

**Comment by mariolukas** [comment]
JC_Button ist eine Library die noch über die Arduino IDE nach installiert werden muss.
Werkzeuge -> Bibliotheken Verwalten , dort nach JC_Button suchen und installieren.

**Comment by awatterott** [comment]
Die `JC_Button` Lib ist mit im CO2-Ampel Board seit einiger Zeit.
Am besten mal die IDE neustarten nachdem alle Boards installiert wurden.
Um was für ein Betriebssystem handelt es sich?

**Comment by Enoch23** [comment]
macOS Big Sur 11.3

Ein Neustarten der IDE hat bis jetzt nichts gebracht. Ich kann es heute Nachmittag nochmal testen.

**Comment by awatterott** [comment]
Geht das Kompilieren des `Examples -> Basics -> Blink` Beispiels beim `Arduino SAMD -> Arduino MKR1000` Board?
Da es nach einem generellen Problem aussieht.

**Comment by Enoch23** [comment]
Vielen Dank für die Hilfe. Ich habe dieses Board ausgewählt:

![Boardauswahl](https://user-images.githubusercontent.com/45469688/120698452-60f63080-c4af-11eb-8e11-88530e352de7.png)

Welches Beispiel sollte ich laden? Unter "Examples for Arduino MKR1000" gibt es kein `Basics -> Blink`.

![Exampleauswahl](https://user-images.githubusercontent.com/45469688/120698656-9f8beb00-c4af-11eb-8321-f13763fa7dcc.png)

Ich habe es mit dem `01.Basics -> Blink` versucht. Es kommt die gleiche Meldung.

![Blink](https://user-images.githubusercontent.com/45469688/120699067-36f13e00-c4b0-11eb-9a3a-1548365eae13.png)

Oder habe ich irgendwie die Falsche Arduino SAMD Bibliothek installiert?

**Comment by mariolukas** [comment]
Was für einen Mac verwendest du und welches MacOS? Hast du mal das C02 Ampel Board Support Package versucht?

**Comment by awatterott** [comment]
Wenn das Standard-Beispiel `01.Basics -> Blink` auch nicht funktioniert, dann hat irgendetwas bei der Installation der *Arduino SAMD Boards* nicht funktioniert. Daher alles einmal deinstallieren und dann neu installieren. Falls die Fehlermeldung dann immer noch kommt, den kompletten `/Library/Arduino15/` Ordner löschen und anschließend die Boards erneut installieren. Der Ordner enthält alle Arduino Einstellungen und zusätzliche Boards.

**Comment by awatterott** [comment]
@Enoch23 Funktioniert das Kompilieren jetzt?

**Comment by Enoch23** [comment]
Ich musste den `/Library/Arduino15/` Ordner löschen. Danach habe ich die SAMD-Boards Installiert, die IDE beendet, den CO2-Board installiert, die IDE beendet und dann das Kompilieren nochmal versucht. Jetzt klappt es! Danke!

So sieht die Ausgabe der IDE aus:
`WARNING: library JC_Button claims to run on avr architecture(s) and may be incompatible with your current board which runs on samd architecture(s).
Sketch uses 78980 bytes (30%) of program storage space. Maximum is 262144 bytes.
Global variables use 6780 bytes of dynamic memory.`

Ich konnte den AP-Modus starten und kann jetzt auf die Web-Oberfläche zugreifen:

![Screenshot 2021-06-12 at 12 23 29](https://user-images.githubusercontent.com/45469688/121772964-383dfd00-cb79-11eb-9eb7-ecb77711b202.png)

Warum sehe ich die Helligkeit nicht? Muss ich etwas in `config.h` anpassen?

**Comment by mariolukas** [comment]
Da das Problem scheinbar gelöst wurde schließe ich dieses Issue.

**Comment by awatterott** [comment]
> Warum sehe ich die Helligkeit nicht? Muss ich etwas in `config.h` anpassen?

Die Helligkeit wird nur jede 30min geprüft, da man dazu die LEDs ausschalten muss:
https://github.com/mariolukas/Watterott-CO2-Ampel-Plus-Firmware/blob/main/CO2-Ampel_Plus/Config.h#L81
