### ISSUE TITLE
Webserver startet im AP Modus nicht

### ISSUE THREAD

**Issue by QueerCodingGirl** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#28]
Firmware Version: v.2.2.0

Wenn ich die Ampel in den AP Modus versetze und zu dem AP eine Verbindung aufbaue, kann ich die 192.168.1.1 zwar pingen, aber ich bekomme auf Port 80 nur ein Connection Refused. Das deutet für mich darauf hin das der Webserver nicht wie erwartet startet.

Habt ihr irgendeine Idee woran das liegen könnte und wie ich jetzt weiter debuggen sollte? Oder kann den Fehler jemand mit der aktuellen Firmware reproduzieren? Ich hab die .BIN von den Github Releases heruntergeladen und nicht selbst gebaut / editiert.

Auf der Serial sieht das so aus:

```
Creating Access Point

SSID: CO2 Ampel F0:F8

IP Address: 192.168.1.1

Signal strength (RSSI): -100 dBm

Device connected to AP

```

**Comment by awatterott** [comment]
Funktioniert die Verbindung zum WebServer mit der [normalen Firmware](https://learn.watterott.com/breakouts/co2-ampel/getting-started/#firmware) (ohne MQTT)?

**Comment by QueerCodingGirl** [comment]
Mit der standard Firmware (v14) kriege ich die Ampel noch nicht einmal in den AP Modus versetzt. Ich kann die Helligkeit der LEDs mit dem SwitchMode Button verändern, aber egal wie lange ich den gedrückt halte, es spawnt kein Wifi.
Hab ich vielleicht einfach ein schlechtes Teil aus der Produktion erwischt?

Danke für den Support! :)

**Comment by awatterott** [comment]
Alles klar. Ja, dann kann es ein Hardwareproblem sein. Bitte einmal per Mail melden: support at watterott dot com

**Comment by QueerCodingGirl** [comment]
Super schneller und kompetenter Support! Hardware Problem ist jetzt durch Software gelöst. xD
Ein Firmware Update mit einem Fix ist jetzt online (v15).
Jetzt geht das WLAN im AP Modus und WPA Modus und die Webseite lässt sich auch laden. Mir ist erstmal geholfen, aber ich lasse den Issue mal offen bis für diese Firmware auch ein Update raus ist. MQTT wäre schon toll ;)

**Comment by QueerCodingGirl** [comment]
@mariolukas Ein Kommentar beim schließen wäre toll. Ist das WLAN hier inzwischen auch gefixt?

**Comment by awatterott** [comment]
Ja, das funktioniert. Das Problem war die Erstellung der Firmware mit einem älteren [CO2-Ampel BSP](https://github.com/watterott/CO2-Ampel/tree/master/arduino#board-support-package), welches noch nicht mit der Hardware der Pro-Version der CO2-Ampel kompatibel war.

**Comment by mariolukas** [comment]
@QueerCodingGirl sorry. Das issue war schon so lange auf und ich dachte nach @awatterott's Antwort sei das gelöst. Also  eigentlich sollte das mit dem AP auch funktionieren. Ich kann den Fehler jedenfalls nicht reproduzieren.

**Comment by Gruman88** [comment]
Salü
Gestern meine CO2-Ampel Pro erhalten. Gleich die Firmware CO2-Ampel_Plus.v.3.0.1.bin geladen, jedoch habe ich ein ähnliches Problem.
Direkt nach dem Flashen kann ich den AP Modus nicht korrekt starten -> Blaues Blinken statt konstantes Leuchten.
Nach einem Reset kann ich dann aber den AP Modus starten -> Alle 4 RGB leuchten Blau und der Access Point kann über WLAN gefunden und verbunden werden (PW: co2admin).

Über Serial kriege ich dann ein "Device connected to AP".
Sobal dich aber über die http://192.168.1.1 darauf zugreifen will, kriege ich folgendes:
"ERR_CONNECTION_REFUSED"

Über den Serial kriege ich folgende Meldungen:
[WIFI] handleClient: New Client
[WIFI] handleClient: Client disconnected
[WIFI] handleClient: Don't keepCurrentClient
[WIFI] handleClient: Client disconnected

Versucht habe ich die Verbindung von meinem privaten Rechner, meinem Handy und nun gerade am Notebook im Geschäft. Überall das gleiche.

Laden der SSID über die Originale Watterott Firmware hatte geklappt, somit schient das WLAN Modul i.O zu sein.
Mit dem IPScanner kann die CO2 Ampel sehen und auch Pingen klappt ohne Probleme.

Für jede Hilfe wäre ich Dankbar :)

Grüsse aus der Schweiz

**Comment by QueerCodingGirl** [comment]
Ich kam auch noch nicht dazu von der Original Firmware zu dieser hier zu wechseln und zu testen. Ich vermute also das es hier den Fehler einfach noch gibt und ein Bugfix für hier vielleicht in der Original Firmware zu finden wäre.

**Comment by mariolukas** [comment]
Ich prüfe noch einmal ob das BSP vielleicht nicht aktuell ist.

**Comment by QueerCodingGirl** [comment]
@mariolukas Bist du schon zum nachschauen/testen gekommen?
