### ISSUE TITLE
Could you provide a json endpoint?

### ISSUE THREAD

**Issue by ldidry** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#29]
Hello,

Thank you for your great work! Would it be possible to have a json endpoint (like `/values.json`) containing the current values of the sensors? It would allow a more simple and hackable way to use the device.

For example, I prefer to use a simple Munin plugin to get the data. For now, I need to parse the HTML page, which is not pretty and may easily not work in the future.

Thank you,

**Comment by mariolukas** [comment]
Sure should be possible.

**Comment by mariolukas** [comment]
Solved within 3.0.0 (dc98c6cb00c95066980131883c7f518c27a2acfb)
