### ISSUE TITLE
Not compiling with DISPLAY_AUSGABE

### ISSUE THREAD

**Issue by scurfin** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#3]
Compiling the firmware with the Config.h file available here works without errors.

When I try to compile the firmware with DISPLAY_AUSGABE 1, I get an error in the Sensor.cpp file (line 36):

```
sketch\Sensor.cpp: In function 'void show_data()':
Sensor.cpp:36:5: error: 'display' was not declared in this scope
     display.clearDisplay();
     ^~~~~~~
sketch\Sensor.cpp:36:5: note: suggested alternative: 'delay'
     display.clearDisplay();
     ^~~~~~~
     delay
CO2-Ampel_Plus:39:1: error: 'Adafruit_SSD1306' does not name a type
 Adafruit_SSD1306 display(128, 64); //128x64 Pixel
 ^~~~~~~~~~~~~~~~
exit status 1
'display' was not declared in this scope
```

Do I need to configure something else in another place?

**Comment by awatterott** [comment]
I have made some changes. Can you try the new version.

**Comment by scurfin** [comment]
Thanks for the quick fix, compiling now runs through without errors.
Couldn't test it on the hardware yet though.
