### ISSUE TITLE
Kein Kompilieren mit Display_Ausgabe

### ISSUE THREAD

**Issue by Enoch23** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#30]
Ich habe `Display_Ausgabe` auf `1` gesetzt in der `Config.h.` Beim Kompilieren Kommt folgendes:

`WARNING: library JC_Button claims to run on avr architecture(s) and may be incompatible with your current board which runs on samd architecture(s).
    In file included from /Users/pilgrim/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/Arduino.h:48:0,
                     from sketch/Sensor.h:3,
                     from sketch/Sensor.cpp:1:
    /Users/pilgrim/Library/Arduino15/packages/co2ampel/hardware/samd/1.0.7/variants/co2ampel/variant.h:197:37: error: 'SerialUSB' does not name a type
     #define Serial                      SerialUSB
                                         ^
    sketch/Sensor.cpp:17:1: note: in expansion of macro 'Serial'
     Serial.println("Use SSD1306 display")
     ^~~~~~`

Ich habe die Zeile `Serial.println("Use SSD1306 display")` auskommentiert und konnte dann erfolgreich Kompilieren. Das Display funktioniert allerdings nicht.

P.S. Die Ausgabe des Arduino-IDEs war deutlich länger. Ich kann auch wenn nötig den gesamten Text hier Veröffentlichen.

**Comment by awatterott** [comment]
Danke für den Hinweis mit `Serial.print`.

Um was für ein Display handelt es sich und ist die Addresse auf `0x3D` gesetzt (DC/SA0 Pin = High)?
