### ISSUE TITLE
Does not work with new Model

### ISSUE THREAD

**Issue by danst0** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#43]
Hi,

I tried uploading the new firmware to the new model (https://shop.watterott.com/CO2-Ampel-pro-USB-WiFi). Only the small red LED shines all the time. CO2 Ampel function is broken since. ;-(

Daniel

**Comment by mariolukas** [comment]
Is this fixed?

**Comment by danst0** [comment]
The issue was that MacOS does not seem to play nice with the firmware upload mechanism. I had to use a windows PC.
