### ISSUE TITLE
Calibration missing??

### ISSUE THREAD

**Issue by btittelbach** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#47]
Hi,

My two CO2-Ampel are offset by 400ppm even when next to each other. Very likely they need calibration.
How is calibration handled with the firmare? I was not able to find any evidence that it is implemented.

- in `sensors.cpp` I found a function() for calibration, but it does not seem to be called by anything.
- in `CO2-Ampel_Plus.ino` there is a comment describing the buttons one needs to press for calibration, but this seems to refer to the original watterott firmware and not work with this firmware
- In Issue #7  someone already asked this question, but it was not answered

If you have plans to implement calibration
- what is the plan? / timeline? / current state? / current problems with that?
- anything I can do to help and code this over the next few days?

**Comment by mariolukas** [comment]
> what is the plan? / timeline? / current state? / current problems with that?

This code was derived from a very early version of the Watterott Firmware. I added the calibration routine, but it was never fully implemented. I think the calibration process needs more than only the code. We will also need a part in the documentation. As far as i know do those SCD based Co2 Sensors need a couple of hours/days for calibrating. Best case of calibrating is outside in the fresh air. But i am not sure about that, somebody should do some research by reading the datasheet.

There is no plan/timeline now. I don't have the time to implement it yet. But and that leads to the next point.... 

> anything I can do to help and code this over the next few days?

Feel free to do an implementation and a PR. I would appreciate it.

**Comment by btittelbach** [comment]
The above mentioned pullrequest should fix this issue
