### ISSUE TITLE
[2.0.0] Startet erst wenn Serial Monitor (Arduino IDE) aktiviert ist

### ISSUE THREAD

**Issue by reibuehl** [mariolukas/Watterott-CO2-Ampel-Plus-Firmware#9]
Ich hab gerade mal die 2.0.0 gebaut und habe nun das komische Verhalten, dass die CO2 Ampel erst "startet", wenn ich den Serial Monitor in der Arduino IDE anschalte. An einer Powerbank oder am PC ohne geöffneten Serial Monitor erfolgt kein LED Test oder ähnliches, nur eine orange LED auf dem SCD30 Sensorboard blinkt langsam und schwach im geschätzt 3 Sekunden Takt.

**Comment by awatterott** [comment]
Das ` while (!Serial)` am Anfang von `void setup()` muss rausgenommen werden oder darf nur beim Debuggen ausgeführt werden.

**Comment by reibuehl** [comment]
Danke!

Mit einem `#if DEBUG_LOG > 0` und `#endif` drum funktioniert es.

**Comment by awatterott** [comment]
Danke, ich habe den PR übernommen.
